public class A1_HowToMove extends World {

    public void go() {


        System.out.println("Thai curry or Baked Feta or eggplant tomato motzerella or haloumi dipped in tazkiki or Nai-Nai's Chinese Food");
        plane.pausetime = 1;
        plane.teleport(50,52);
        plane.startingAngle(0);
        plane.trailWidth=2;
        plane.setColor(24,184,77);
        plane.isTrail = true;
        plane.move(100);
        plane.turn(-90);
        plane.move(5);
        plane.turn(90);
        plane.move(50);
        plane.turn(-90);
        plane.move(20);
        plane.turn(-90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(15);
        plane.turn(-45);
        plane.move(20);
        plane.turn(-42);
        plane.move(20);
        plane.turn(-45);
        plane.move(50);
        plane.turn(-90);
        plane.move(50);
        plane.turn(-150);
        plane.move(35);
        plane.turn(80);
        plane.move(20);
        plane.turn(98);
        plane.move(5);

        plane.isTrail=false;
        plane.move(30);
        plane.turn(10);
        plane.move(60);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth = 3;
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.isTrail=false;
        plane.move(60);
        plane.turn(180);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth=2;
        plane.move(20);
        plane.isTrail=false;
        plane.move(300);


        plane.teleport(770,47);
        plane.trailWidth=2;
        plane.setColor(24,184,77);
        plane.isTrail = true;
        plane.move(100);
        plane.turn(-90);
        plane.move(5);
        plane.turn(90);
        plane.move(50);
        plane.turn(-90);
        plane.move(20);
        plane.turn(-90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(15);
        plane.turn(-45);
        plane.move(20);
        plane.turn(-42);
        plane.move(20);
        plane.turn(-45);
        plane.move(50);
        plane.turn(-90);
        plane.move(50);
        plane.turn(-150);
        plane.move(35);
        plane.turn(80);
        plane.move(20);
        plane.turn(98);
        plane.move(5);

        plane.isTrail=false;
        plane.move(30);
        plane.turn(10);
        plane.move(60);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth = 3;
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.isTrail=false;
        plane.move(60);
        plane.turn(180);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth=2;
        plane.move(20);
        plane.isTrail=false;
        plane.move(300);


        plane.teleport(738,650);
        plane.trailWidth=2;
        plane.setColor(24,184,77);
        plane.isTrail = true;
        plane.move(100);
        plane.turn(-90);
        plane.move(5);
        plane.turn(90);
        plane.move(50);
        plane.turn(-90);
        plane.move(20);
        plane.turn(-90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(15);
        plane.turn(-45);
        plane.move(20);
        plane.turn(-42);
        plane.move(20);
        plane.turn(-45);
        plane.move(50);
        plane.turn(-90);
        plane.move(50);
        plane.turn(-150);
        plane.move(35);
        plane.turn(80);
        plane.move(20);
        plane.turn(98);
        plane.move(5);

        plane.isTrail=false;
        plane.move(30);
        plane.turn(10);
        plane.move(60);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth = 3;
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.isTrail=false;
        plane.move(60);
        plane.turn(180);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth=2;
        plane.move(20);
        plane.isTrail=false;
        plane.move(300);


        plane.teleport(237,696);
        plane.trailWidth=2;
        plane.setColor(24,184,77);
        plane.isTrail = true;
        plane.move(100);
        plane.turn(-90);
        plane.move(5);
        plane.turn(90);
        plane.move(50);
        plane.turn(-90);
        plane.move(20);
        plane.turn(-90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(15);
        plane.turn(-45);
        plane.move(20);
        plane.turn(-42);
        plane.move(20);
        plane.turn(-45);
        plane.move(50);
        plane.turn(-90);
        plane.move(50);
        plane.turn(-150);
        plane.move(35);
        plane.turn(80);
        plane.move(20);
        plane.turn(98);
        plane.move(5);

        plane.isTrail=false;
        plane.move(30);
        plane.turn(10);
        plane.move(60);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth = 3;
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.isTrail=false;
        plane.move(60);
        plane.turn(180);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth=2;
        plane.move(20);
        plane.isTrail=false;
        plane.move(300);

        plane.teleport(281,320);
        plane.trailWidth=2;
        plane.setColor(24,184,77);
        plane.isTrail = true;
        plane.move(100);
        plane.turn(-90);
        plane.move(5);
        plane.turn(90);
        plane.move(50);
        plane.turn(-90);
        plane.move(20);
        plane.turn(-90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(15);
        plane.turn(-45);
        plane.move(20);
        plane.turn(-42);
        plane.move(20);
        plane.turn(-45);
        plane.move(50);
        plane.turn(-90);
        plane.move(50);
        plane.turn(-150);
        plane.move(35);
        plane.turn(80);
        plane.move(20);
        plane.turn(98);
        plane.move(5);

        plane.isTrail=false;
        plane.move(30);
        plane.turn(10);
        plane.move(60);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth = 3;
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.isTrail=false;
        plane.move(60);
        plane.turn(180);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth=2;
        plane.move(20);
        plane.isTrail=false;
        plane.move(300);

        plane.teleport(718,284);
        plane.trailWidth=2;
        plane.setColor(24,184,77);
        plane.isTrail = true;
        plane.move(100);
        plane.turn(-90);
        plane.move(5);
        plane.turn(90);
        plane.move(50);
        plane.turn(-90);
        plane.move(20);
        plane.turn(-90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(15);
        plane.turn(-45);
        plane.move(20);
        plane.turn(-42);
        plane.move(20);
        plane.turn(-45);
        plane.move(50);
        plane.turn(-90);
        plane.move(50);
        plane.turn(-150);
        plane.move(35);
        plane.turn(80);
        plane.move(20);
        plane.turn(98);
        plane.move(5);

        plane.isTrail=false;
        plane.move(30);
        plane.turn(10);
        plane.move(60);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth = 3;
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.isTrail=false;
        plane.move(60);
        plane.turn(180);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth=2;
        plane.move(20);
        plane.isTrail=false;
        plane.move(300);

        plane.teleport(354,514);
        plane.trailWidth=2;
        plane.setColor(24,184,77);
        plane.isTrail = true;
        plane.move(100);
        plane.turn(-90);
        plane.move(5);
        plane.turn(90);
        plane.move(50);
        plane.turn(-90);
        plane.move(20);
        plane.turn(-90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(70);
        plane.turn(90);
        plane.move(10);
        plane.turn(-90);
        plane.move(5);
        plane.turn(-90);
        plane.move(10);
        plane.turn(90);
        plane.move(15);
        plane.turn(-45);
        plane.move(20);
        plane.turn(-42);
        plane.move(20);
        plane.turn(-45);
        plane.move(50);
        plane.turn(-90);
        plane.move(50);
        plane.turn(-150);
        plane.move(35);
        plane.turn(80);
        plane.move(20);
        plane.turn(98);
        plane.move(5);

        plane.isTrail=false;
        plane.move(30);
        plane.turn(10);
        plane.move(60);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth = 3;
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.move(2);
        plane.turn(90);
        plane.isTrail=false;
        plane.move(60);
        plane.turn(180);
        plane.isTrail=true;
        plane.setColor(3,28,11);
        plane.trailWidth=2;
        plane.move(20);
        plane.isTrail=false;
        plane.move(300);
        plane.isTrail=true;

        plane.trailWidth=2;
        plane.teleport((int)(Math.random() *600),((int)(Math.random() *600)));
        plane.setColor((int)(Math.random() * 256), (int)(Math.random() * 256),(int)(Math.random() * 256));
        house();
        plane.teleport((int)(Math.random() *600),((int)(Math.random() *600)));
        plane.trailWidth=plane.trailWidth+1;
        house();
        plane.teleport((int)(Math.random() *600),((int)(Math.random() *600)));
        plane.trailWidth=plane.trailWidth+1;
        house();
        plane.teleport((int)(Math.random() *600),((int)(Math.random() *600)));
        plane.trailWidth=plane.trailWidth+1;
        house();
        plane.teleport((int)(Math.random() *600),((int)(Math.random() *600)));
        plane.trailWidth=plane.trailWidth+1;
        house();
        plane.teleport((int)(Math.random() *600),((int)(Math.random() *600)));
        plane.trailWidth=plane.trailWidth+1;
        house();
        plane.teleport((int)(Math.random() *600),((int)(Math.random() *600)));
        plane.trailWidth=plane.trailWidth+1;
        house();



















    };
public void house() {
        plane.isTrail=true;
        int size=100;
        plane.startingAngle(0);
        plane.move(size);
        plane.turn(90);
        plane.move(size);
        plane.turn(90);
        plane.move(size);
        plane.turn(90);
        plane.move(size);
        plane.turn(90);
        plane.turn(90);
        plane.move(size);
        plane.turn(-42);
        plane.move(70);
        plane.turn(-90);
        plane.move(75);








}
}

